// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: protos/server.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubsrcribeResponse_MESSAGE_TYPE int32

const (
	SubsrcribeResponse_EVENT         SubsrcribeResponse_MESSAGE_TYPE = 0 // Server log message
	SubsrcribeResponse_UPLOAD_STATUS SubsrcribeResponse_MESSAGE_TYPE = 1 // Upload Status Message
	SubsrcribeResponse_UPLOAD_CANCEL SubsrcribeResponse_MESSAGE_TYPE = 2 // Upload was cancelled
)

// Enum value maps for SubsrcribeResponse_MESSAGE_TYPE.
var (
	SubsrcribeResponse_MESSAGE_TYPE_name = map[int32]string{
		0: "EVENT",
		1: "UPLOAD_STATUS",
		2: "UPLOAD_CANCEL",
	}
	SubsrcribeResponse_MESSAGE_TYPE_value = map[string]int32{
		"EVENT":         0,
		"UPLOAD_STATUS": 1,
		"UPLOAD_CANCEL": 2,
	}
)

func (x SubsrcribeResponse_MESSAGE_TYPE) Enum() *SubsrcribeResponse_MESSAGE_TYPE {
	p := new(SubsrcribeResponse_MESSAGE_TYPE)
	*p = x
	return p
}

func (x SubsrcribeResponse_MESSAGE_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubsrcribeResponse_MESSAGE_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_agent_proto_enumTypes[0].Descriptor()
}

func (SubsrcribeResponse_MESSAGE_TYPE) Type() protoreflect.EnumType {
	return &file_protos_agent_proto_enumTypes[0]
}

func (x SubsrcribeResponse_MESSAGE_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubsrcribeResponse_MESSAGE_TYPE.Descriptor instead.
func (SubsrcribeResponse_MESSAGE_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_protos_agent_proto_rawDescGZIP(), []int{1, 0}
}

type ListFilesResponse_STATUS_TYPE int32

const (
	ListFilesResponse_INDEXED   ListFilesResponse_STATUS_TYPE = 0 // File indexed locally
	ListFilesResponse_SYNCED    ListFilesResponse_STATUS_TYPE = 1 // File manifest synchronized with Cloud
	ListFilesResponse_UPLOADING ListFilesResponse_STATUS_TYPE = 3 // File being uploaded
	ListFilesResponse_COMPLETED ListFilesResponse_STATUS_TYPE = 4 // File completed uploading
	ListFilesResponse_CANCELED  ListFilesResponse_STATUS_TYPE = 5 // File Upload canceled (manually, or failed)
)

// Enum value maps for ListFilesResponse_STATUS_TYPE.
var (
	ListFilesResponse_STATUS_TYPE_name = map[int32]string{
		0: "INDEXED",
		1: "SYNCED",
		3: "UPLOADING",
		4: "COMPLETED",
		5: "CANCELED",
	}
	ListFilesResponse_STATUS_TYPE_value = map[string]int32{
		"INDEXED":   0,
		"SYNCED":    1,
		"UPLOADING": 3,
		"COMPLETED": 4,
		"CANCELED":  5,
	}
)

func (x ListFilesResponse_STATUS_TYPE) Enum() *ListFilesResponse_STATUS_TYPE {
	p := new(ListFilesResponse_STATUS_TYPE)
	*p = x
	return p
}

func (x ListFilesResponse_STATUS_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListFilesResponse_STATUS_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_agent_proto_enumTypes[1].Descriptor()
}

func (ListFilesResponse_STATUS_TYPE) Type() protoreflect.EnumType {
	return &file_protos_agent_proto_enumTypes[1]
}

func (x ListFilesResponse_STATUS_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListFilesResponse_STATUS_TYPE.Descriptor instead.
func (ListFilesResponse_STATUS_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_protos_agent_proto_rawDescGZIP(), []int{11, 0}
}

type SubscribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_agent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_protos_agent_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SubsrcribeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type SubsrcribeResponse_MESSAGE_TYPE `protobuf:"varint,8,opt,name=type,proto3,enum=protos.SubsrcribeResponse_MESSAGE_TYPE" json:"type,omitempty"`
	// Types that are assignable to MessageData:
	//	*SubsrcribeResponse_UploadStatus
	//	*SubsrcribeResponse_EventInfo
	MessageData isSubsrcribeResponse_MessageData `protobuf_oneof:"message_data"`
}

func (x *SubsrcribeResponse) Reset() {
	*x = SubsrcribeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_agent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubsrcribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubsrcribeResponse) ProtoMessage() {}

func (x *SubsrcribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubsrcribeResponse.ProtoReflect.Descriptor instead.
func (*SubsrcribeResponse) Descriptor() ([]byte, []int) {
	return file_protos_agent_proto_rawDescGZIP(), []int{1}
}

func (x *SubsrcribeResponse) GetType() SubsrcribeResponse_MESSAGE_TYPE {
	if x != nil {
		return x.Type
	}
	return SubsrcribeResponse_EVENT
}

func (m *SubsrcribeResponse) GetMessageData() isSubsrcribeResponse_MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (x *SubsrcribeResponse) GetUploadStatus() *SubsrcribeResponse_UploadResponse {
	if x, ok := x.GetMessageData().(*SubsrcribeResponse_UploadStatus); ok {
		return x.UploadStatus
	}
	return nil
}

func (x *SubsrcribeResponse) GetEventInfo() *SubsrcribeResponse_EventResponse {
	if x, ok := x.GetMessageData().(*SubsrcribeResponse_EventInfo); ok {
		return x.EventInfo
	}
	return nil
}

type isSubsrcribeResponse_MessageData interface {
	isSubsrcribeResponse_MessageData()
}

type SubsrcribeResponse_UploadStatus struct {
	UploadStatus *SubsrcribeResponse_UploadResponse `protobuf:"bytes,9,opt,name=uploadStatus,proto3,oneof"`
}

type SubsrcribeResponse_EventInfo struct {
	EventInfo *SubsrcribeResponse_EventResponse `protobuf:"bytes,10,opt,name=eventInfo,proto3,oneof"`
}

func (*SubsrcribeResponse_UploadStatus) isSubsrcribeResponse_MessageData() {}

func (*SubsrcribeResponse_EventInfo) isSubsrcribeResponse_MessageData() {}

type SimpleStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *SimpleStatusResponse) Reset() {
	*x = SimpleStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_agent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimpleStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleStatusResponse) ProtoMessage() {}

func (x *SimpleStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleStatusResponse.ProtoReflect.Descriptor instead.
func (*SimpleStatusResponse) Descriptor() ([]byte, []int) {
	return file_protos_agent_proto_rawDescGZIP(), []int{2}
}

func (x *SimpleStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CancelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ManifestId string `protobuf:"bytes,1,opt,name=manifestId,proto3" json:"manifestId,omitempty"`
	CancelAll  bool   `protobuf:"varint,2,opt,name=cancelAll,proto3" json:"cancelAll,omitempty"`
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_agent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_protos_agent_proto_rawDescGZIP(), []int{3}
}

func (x *CancelRequest) GetManifestId() string {
	if x != nil {
		return x.ManifestId
	}
	return ""
}

func (x *CancelRequest) GetCancelAll() bool {
	if x != nil {
		return x.CancelAll
	}
	return false
}

type CreateManifestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasePath       string `protobuf:"bytes,1,opt,name=basePath,proto3" json:"basePath,omitempty"`
	TargetBasePath string `protobuf:"bytes,2,opt,name=targetBasePath,proto3" json:"targetBasePath,omitempty"`
	Recursive      bool   `protobuf:"varint,3,opt,name=recursive,proto3" json:"recursive,omitempty"`
}

func (x *CreateManifestRequest) Reset() {
	*x = CreateManifestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_agent_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateManifestRequest) ProtoMessage() {}

func (x *CreateManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateManifestRequest.ProtoReflect.Descriptor instead.
func (*CreateManifestRequest) Descriptor() ([]byte, []int) {
	return file_protos_agent_proto_rawDescGZIP(), []int{4}
}

func (x *CreateManifestRequest) GetBasePath() string {
	if x != nil {
		return x.BasePath
	}
	return ""
}

func (x *CreateManifestRequest) GetTargetBasePath() string {
	if x != nil {
		return x.TargetBasePath
	}
	return ""
}

func (x *CreateManifestRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type AddManifestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ManifestId     string `protobuf:"bytes,1,opt,name=manifestId,proto3" json:"manifestId,omitempty"`
	BasePath       string `protobuf:"bytes,2,opt,name=basePath,proto3" json:"basePath,omitempty"`
	TargetBasePath string `protobuf:"bytes,3,opt,name=targetBasePath,proto3" json:"targetBasePath,omitempty"`
	Recursive      bool   `protobuf:"varint,4,opt,name=recursive,proto3" json:"recursive,omitempty"`
}

func (x *AddManifestRequest) Reset() {
	*x = AddManifestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_agent_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddManifestRequest) ProtoMessage() {}

func (x *AddManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddManifestRequest.ProtoReflect.Descriptor instead.
func (*AddManifestRequest) Descriptor() ([]byte, []int) {
	return file_protos_agent_proto_rawDescGZIP(), []int{5}
}

func (x *AddManifestRequest) GetManifestId() string {
	if x != nil {
		return x.ManifestId
	}
	return ""
}

func (x *AddManifestRequest) GetBasePath() string {
	if x != nil {
		return x.BasePath
	}
	return ""
}

func (x *AddManifestRequest) GetTargetBasePath() string {
	if x != nil {
		return x.TargetBasePath
	}
	return ""
}

func (x *AddManifestRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type RemoveFromManifestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ManifestId string  `protobuf:"bytes,1,opt,name=manifestId,proto3" json:"manifestId,omitempty"`
	FileId     []int32 `protobuf:"varint,2,rep,packed,name=fileId,proto3" json:"fileId,omitempty"`
}

func (x *RemoveFromManifestRequest) Reset() {
	*x = RemoveFromManifestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_agent_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveFromManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromManifestRequest) ProtoMessage() {}

func (x *RemoveFromManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromManifestRequest.ProtoReflect.Descriptor instead.
func (*RemoveFromManifestRequest) Descriptor() ([]byte, []int) {
	return file_protos_agent_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveFromManifestRequest) GetManifestId() string {
	if x != nil {
		return x.ManifestId
	}
	return ""
}

func (x *RemoveFromManifestRequest) GetFileId() []int32 {
	if x != nil {
		return x.FileId
	}
	return nil
}

type ManifestStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ManifestStatusRequest) Reset() {
	*x = ManifestStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_agent_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManifestStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestStatusRequest) ProtoMessage() {}

func (x *ManifestStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestStatusRequest.ProtoReflect.Descriptor instead.
func (*ManifestStatusRequest) Descriptor() ([]byte, []int) {
	return file_protos_agent_proto_rawDescGZIP(), []int{7}
}

type ManifestStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Manifests []*ManifestStatusResponse_Manifest `protobuf:"bytes,1,rep,name=manifests,proto3" json:"manifests,omitempty"`
}

func (x *ManifestStatusResponse) Reset() {
	*x = ManifestStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_agent_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManifestStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestStatusResponse) ProtoMessage() {}

func (x *ManifestStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestStatusResponse.ProtoReflect.Descriptor instead.
func (*ManifestStatusResponse) Descriptor() ([]byte, []int) {
	return file_protos_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ManifestStatusResponse) GetManifests() []*ManifestStatusResponse_Manifest {
	if x != nil {
		return x.Manifests
	}
	return nil
}

type DeleteManifestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ManifestId string `protobuf:"bytes,1,opt,name=manifest_id,json=manifestId,proto3" json:"manifest_id,omitempty"`
}

func (x *DeleteManifestRequest) Reset() {
	*x = DeleteManifestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_agent_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteManifestRequest) ProtoMessage() {}

func (x *DeleteManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteManifestRequest.ProtoReflect.Descriptor instead.
func (*DeleteManifestRequest) Descriptor() ([]byte, []int) {
	return file_protos_agent_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteManifestRequest) GetManifestId() string {
	if x != nil {
		return x.ManifestId
	}
	return ""
}

type ListFilesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ManifestId string `protobuf:"bytes,1,opt,name=manifest_id,json=manifestId,proto3" json:"manifest_id,omitempty"`
	Offset     int32  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit      int32  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_agent_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_protos_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ListFilesRequest) GetManifestId() string {
	if x != nil {
		return x.ManifestId
	}
	return ""
}

func (x *ListFilesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListFilesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListFilesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File []*ListFilesResponse_FileUpload `protobuf:"bytes,1,rep,name=file,proto3" json:"file,omitempty"`
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_agent_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_protos_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ListFilesResponse) GetFile() []*ListFilesResponse_FileUpload {
	if x != nil {
		return x.File
	}
	return nil
}

type UploadManifestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ManifestId string `protobuf:"bytes,1,opt,name=manifest_id,json=manifestId,proto3" json:"manifest_id,omitempty"`
}

func (x *UploadManifestRequest) Reset() {
	*x = UploadManifestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_agent_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadManifestRequest) ProtoMessage() {}

func (x *UploadManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadManifestRequest.ProtoReflect.Descriptor instead.
func (*UploadManifestRequest) Descriptor() ([]byte, []int) {
	return file_protos_agent_proto_rawDescGZIP(), []int{12}
}

func (x *UploadManifestRequest) GetManifestId() string {
	if x != nil {
		return x.ManifestId
	}
	return ""
}

type SubsrcribeResponse_EventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Details string `protobuf:"bytes,1,opt,name=Details,proto3" json:"Details,omitempty"`
}

func (x *SubsrcribeResponse_EventResponse) Reset() {
	*x = SubsrcribeResponse_EventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_agent_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubsrcribeResponse_EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubsrcribeResponse_EventResponse) ProtoMessage() {}

func (x *SubsrcribeResponse_EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubsrcribeResponse_EventResponse.ProtoReflect.Descriptor instead.
func (*SubsrcribeResponse_EventResponse) Descriptor() ([]byte, []int) {
	return file_protos_agent_proto_rawDescGZIP(), []int{1, 0}
}

func (x *SubsrcribeResponse_EventResponse) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type SubsrcribeResponse_UploadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileId  string `protobuf:"bytes,1,opt,name=FileId,proto3" json:"FileId,omitempty"`
	Total   int64  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Current int64  `protobuf:"varint,3,opt,name=current,proto3" json:"current,omitempty"`
}

func (x *SubsrcribeResponse_UploadResponse) Reset() {
	*x = SubsrcribeResponse_UploadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_agent_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubsrcribeResponse_UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubsrcribeResponse_UploadResponse) ProtoMessage() {}

func (x *SubsrcribeResponse_UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubsrcribeResponse_UploadResponse.ProtoReflect.Descriptor instead.
func (*SubsrcribeResponse_UploadResponse) Descriptor() ([]byte, []int) {
	return file_protos_agent_proto_rawDescGZIP(), []int{1, 1}
}

func (x *SubsrcribeResponse_UploadResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *SubsrcribeResponse_UploadResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SubsrcribeResponse_UploadResponse) GetCurrent() int64 {
	if x != nil {
		return x.Current
	}
	return 0
}

type ManifestStatusResponse_Manifest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserName         string `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserId           string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrganizationName string `protobuf:"bytes,4,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	OrganizationId   string `protobuf:"bytes,5,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	DatasetName      string `protobuf:"bytes,6,opt,name=dataset_name,json=datasetName,proto3" json:"dataset_name,omitempty"`
	DatasetId        string `protobuf:"bytes,7,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	Status           string `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *ManifestStatusResponse_Manifest) Reset() {
	*x = ManifestStatusResponse_Manifest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_agent_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManifestStatusResponse_Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestStatusResponse_Manifest) ProtoMessage() {}

func (x *ManifestStatusResponse_Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestStatusResponse_Manifest.ProtoReflect.Descriptor instead.
func (*ManifestStatusResponse_Manifest) Descriptor() ([]byte, []int) {
	return file_protos_agent_proto_rawDescGZIP(), []int{8, 0}
}

func (x *ManifestStatusResponse_Manifest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ManifestStatusResponse_Manifest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ManifestStatusResponse_Manifest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ManifestStatusResponse_Manifest) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *ManifestStatusResponse_Manifest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ManifestStatusResponse_Manifest) GetDatasetName() string {
	if x != nil {
		return x.DatasetName
	}
	return ""
}

func (x *ManifestStatusResponse_Manifest) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

func (x *ManifestStatusResponse_Manifest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListFilesResponse_FileUpload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32                         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId  string                        `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SourcePath string                        `protobuf:"bytes,3,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	TargetPath string                        `protobuf:"bytes,4,opt,name=target_path,json=targetPath,proto3" json:"target_path,omitempty"`
	S3Key      string                        `protobuf:"bytes,5,opt,name=s3_key,json=s3Key,proto3" json:"s3_key,omitempty"`
	Status     ListFilesResponse_STATUS_TYPE `protobuf:"varint,6,opt,name=status,proto3,enum=protos.ListFilesResponse_STATUS_TYPE" json:"status,omitempty"`
}

func (x *ListFilesResponse_FileUpload) Reset() {
	*x = ListFilesResponse_FileUpload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_agent_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFilesResponse_FileUpload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse_FileUpload) ProtoMessage() {}

func (x *ListFilesResponse_FileUpload) ProtoReflect() protoreflect.Message {
	mi := &file_protos_agent_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse_FileUpload.ProtoReflect.Descriptor instead.
func (*ListFilesResponse_FileUpload) Descriptor() ([]byte, []int) {
	return file_protos_agent_proto_rawDescGZIP(), []int{11, 0}
}

func (x *ListFilesResponse_FileUpload) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListFilesResponse_FileUpload) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ListFilesResponse_FileUpload) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *ListFilesResponse_FileUpload) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

func (x *ListFilesResponse_FileUpload) GetS3Key() string {
	if x != nil {
		return x.S3Key
	}
	return ""
}

func (x *ListFilesResponse_FileUpload) GetStatus() ListFilesResponse_STATUS_TYPE {
	if x != nil {
		return x.Status
	}
	return ListFilesResponse_INDEXED
}

var File_protos_agent_proto protoreflect.FileDescriptor

var file_protos_agent_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x22, 0x22, 0x0a, 0x10,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x22, 0xc2, 0x03, 0x0a, 0x12, 0x53, 0x75, 0x62, 0x73, 0x72, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x53,
	0x75, 0x62, 0x73, 0x72, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x4f, 0x0a, 0x0c, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x72, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x48, 0x0a, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x72, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x48, 0x00, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x1a,
	0x29, 0x0a, 0x0d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x1a, 0x58, 0x0a, 0x0e, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x46, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x46, 0x69,
	0x6c, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x22, 0x3f, 0x0a, 0x0c, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x10, 0x00, 0x12,
	0x11, 0x0a, 0x0d, 0x55, 0x50, 0x4c, 0x4f, 0x41, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x50, 0x4c, 0x4f, 0x41, 0x44, 0x5f, 0x43, 0x41, 0x4e,
	0x43, 0x45, 0x4c, 0x10, 0x02, 0x42, 0x0e, 0x0a, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2e, 0x0a, 0x14, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x4d, 0x0a, 0x0d, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65,
	0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x61, 0x6e, 0x69,
	0x66, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c,
	0x41, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x63, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x41, 0x6c, 0x6c, 0x22, 0x79, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x61,
	0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x62, 0x61, 0x73, 0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x62, 0x61, 0x73, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x26, 0x0a, 0x0e, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x42, 0x61, 0x73, 0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x42, 0x61, 0x73, 0x65, 0x50, 0x61, 0x74,
	0x68, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x75, 0x72, 0x73, 0x69, 0x76, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x72, 0x65, 0x63, 0x75, 0x72, 0x73, 0x69, 0x76, 0x65, 0x22,
	0x96, 0x01, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65,
	0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x61, 0x6e, 0x69,
	0x66, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61, 0x73, 0x65, 0x50, 0x61,
	0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x61, 0x73, 0x65, 0x50, 0x61,
	0x74, 0x68, 0x12, 0x26, 0x0a, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x42, 0x61, 0x73, 0x65,
	0x50, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x42, 0x61, 0x73, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65,
	0x63, 0x75, 0x72, 0x73, 0x69, 0x76, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x72,
	0x65, 0x63, 0x75, 0x72, 0x73, 0x69, 0x76, 0x65, 0x22, 0x53, 0x0a, 0x19, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73,
	0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x61, 0x6e, 0x69, 0x66,
	0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x17, 0x0a,
	0x15, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xe2, 0x02, 0x0a, 0x16, 0x4d, 0x61, 0x6e, 0x69, 0x66,
	0x65, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x45, 0x0a, 0x09, 0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4d, 0x61,
	0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x52, 0x09, 0x6d,
	0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x73, 0x1a, 0x80, 0x02, 0x0a, 0x08, 0x4d, 0x61, 0x6e,
	0x69, 0x66, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x11, 0x6f,
	0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x6f, 0x72, 0x67, 0x61,
	0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65,
	0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x38, 0x0a, 0x15, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x61, 0x6e, 0x69, 0x66,
	0x65, 0x73, 0x74, 0x49, 0x64, 0x22, 0x61, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x69, 0x6c,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x6e,
	0x69, 0x66, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0xf7, 0x02, 0x0a, 0x11, 0x4c, 0x69, 0x73,
	0x74, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38,
	0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x1a, 0xd3, 0x01, 0x0a, 0x0a, 0x46, 0x69, 0x6c,
	0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x50, 0x61, 0x74, 0x68, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x33, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x33, 0x4b, 0x65, 0x79, 0x12,
	0x3d, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x69, 0x6c,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x54, 0x41, 0x54, 0x55,
	0x53, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x52,
	0x0a, 0x0b, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x12, 0x0b, 0x0a,
	0x07, 0x49, 0x4e, 0x44, 0x45, 0x58, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x59,
	0x4e, 0x43, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x50, 0x4c, 0x4f, 0x41, 0x44,
	0x49, 0x4e, 0x47, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54,
	0x45, 0x44, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x45, 0x44,
	0x10, 0x05, 0x22, 0x38, 0x0a, 0x15, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x61, 0x6e, 0x69,
	0x66, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6d,
	0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x49, 0x64, 0x32, 0x97, 0x06, 0x0a,
	0x05, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x4f, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x54, 0x6f,
	0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x41, 0x64, 0x64, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x53, 0x69,
	0x6d, 0x70, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72,
	0x6f, 0x6d, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x4d, 0x61,
	0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a,
	0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x12,
	0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d,
	0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x51,
	0x0a, 0x0e, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65,
	0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x4d, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x46, 0x6f,
	0x72, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x4f, 0x0a, 0x0e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65,
	0x73, 0x74, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x53, 0x69, 0x6d, 0x70, 0x6c,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x45, 0x0a, 0x0c, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x53,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x72, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12,
	0x45, 0x0a, 0x0b, 0x55, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x18,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x72, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x65, 0x6e, 0x6e, 0x73, 0x69, 0x65, 0x76, 0x65, 0x2f, 0x70,
	0x65, 0x6e, 0x6e, 0x73, 0x69, 0x65, 0x76, 0x65, 0x2d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_agent_proto_rawDescOnce sync.Once
	file_protos_agent_proto_rawDescData = file_protos_agent_proto_rawDesc
)

func file_protos_agent_proto_rawDescGZIP() []byte {
	file_protos_agent_proto_rawDescOnce.Do(func() {
		file_protos_agent_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_agent_proto_rawDescData)
	})
	return file_protos_agent_proto_rawDescData
}

var file_protos_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protos_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_protos_agent_proto_goTypes = []interface{}{
	(SubsrcribeResponse_MESSAGE_TYPE)(0),      // 0: protos.SubsrcribeResponse.MESSAGE_TYPE
	(ListFilesResponse_STATUS_TYPE)(0),        // 1: protos.ListFilesResponse.STATUS_TYPE
	(*SubscribeRequest)(nil),                  // 2: protos.SubscribeRequest
	(*SubsrcribeResponse)(nil),                // 3: protos.SubsrcribeResponse
	(*SimpleStatusResponse)(nil),              // 4: protos.SimpleStatusResponse
	(*CancelRequest)(nil),                     // 5: protos.CancelRequest
	(*CreateManifestRequest)(nil),             // 6: protos.CreateManifestRequest
	(*AddManifestRequest)(nil),                // 7: protos.AddManifestRequest
	(*RemoveFromManifestRequest)(nil),         // 8: protos.RemoveFromManifestRequest
	(*ManifestStatusRequest)(nil),             // 9: protos.ManifestStatusRequest
	(*ManifestStatusResponse)(nil),            // 10: protos.ManifestStatusResponse
	(*DeleteManifestRequest)(nil),             // 11: protos.DeleteManifestRequest
	(*ListFilesRequest)(nil),                  // 12: protos.ListFilesRequest
	(*ListFilesResponse)(nil),                 // 13: protos.ListFilesResponse
	(*UploadManifestRequest)(nil),             // 14: protos.UploadManifestRequest
	(*SubsrcribeResponse_EventResponse)(nil),  // 15: protos.SubsrcribeResponse.EventResponse
	(*SubsrcribeResponse_UploadResponse)(nil), // 16: protos.SubsrcribeResponse.UploadResponse
	(*ManifestStatusResponse_Manifest)(nil),   // 17: protos.ManifestStatusResponse.Manifest
	(*ListFilesResponse_FileUpload)(nil),      // 18: protos.ListFilesResponse.FileUpload
}
var file_protos_agent_proto_depIdxs = []int32{
	0,  // 0: protos.SubsrcribeResponse.type:type_name -> protos.SubsrcribeResponse.MESSAGE_TYPE
	16, // 1: protos.SubsrcribeResponse.uploadStatus:type_name -> protos.SubsrcribeResponse.UploadResponse
	15, // 2: protos.SubsrcribeResponse.eventInfo:type_name -> protos.SubsrcribeResponse.EventResponse
	17, // 3: protos.ManifestStatusResponse.manifests:type_name -> protos.ManifestStatusResponse.Manifest
	18, // 4: protos.ListFilesResponse.file:type_name -> protos.ListFilesResponse.FileUpload
	1,  // 5: protos.ListFilesResponse.FileUpload.status:type_name -> protos.ListFilesResponse.STATUS_TYPE
	6,  // 6: protos.Agent.CreateManifest:input_type -> protos.CreateManifestRequest
	7,  // 7: protos.Agent.AddToManifest:input_type -> protos.AddManifestRequest
	8,  // 8: protos.Agent.RemoveFromManifest:input_type -> protos.RemoveFromManifestRequest
	11, // 9: protos.Agent.DeleteManifest:input_type -> protos.DeleteManifestRequest
	9,  // 10: protos.Agent.ManifestStatus:input_type -> protos.ManifestStatusRequest
	12, // 11: protos.Agent.ListFilesForManifest:input_type -> protos.ListFilesRequest
	14, // 12: protos.Agent.UploadManifest:input_type -> protos.UploadManifestRequest
	5,  // 13: protos.Agent.CancelUpload:input_type -> protos.CancelRequest
	2,  // 14: protos.Agent.Subscribe:input_type -> protos.SubscribeRequest
	2,  // 15: protos.Agent.Unsubscribe:input_type -> protos.SubscribeRequest
	4,  // 16: protos.Agent.CreateManifest:output_type -> protos.SimpleStatusResponse
	4,  // 17: protos.Agent.AddToManifest:output_type -> protos.SimpleStatusResponse
	4,  // 18: protos.Agent.RemoveFromManifest:output_type -> protos.SimpleStatusResponse
	4,  // 19: protos.Agent.DeleteManifest:output_type -> protos.SimpleStatusResponse
	10, // 20: protos.Agent.ManifestStatus:output_type -> protos.ManifestStatusResponse
	13, // 21: protos.Agent.ListFilesForManifest:output_type -> protos.ListFilesResponse
	4,  // 22: protos.Agent.UploadManifest:output_type -> protos.SimpleStatusResponse
	4,  // 23: protos.Agent.CancelUpload:output_type -> protos.SimpleStatusResponse
	3,  // 24: protos.Agent.Subscribe:output_type -> protos.SubsrcribeResponse
	3,  // 25: protos.Agent.Unsubscribe:output_type -> protos.SubsrcribeResponse
	16, // [16:26] is the sub-list for method output_type
	6,  // [6:16] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_protos_agent_proto_init() }
func file_protos_agent_proto_init() {
	if File_protos_agent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_agent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_agent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubsrcribeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_agent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimpleStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_agent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_agent_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateManifestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_agent_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddManifestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_agent_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveFromManifestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_agent_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManifestStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_agent_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManifestStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_agent_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteManifestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_agent_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFilesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_agent_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFilesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_agent_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadManifestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_agent_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubsrcribeResponse_EventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_agent_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubsrcribeResponse_UploadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_agent_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManifestStatusResponse_Manifest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_agent_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFilesResponse_FileUpload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protos_agent_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*SubsrcribeResponse_UploadStatus)(nil),
		(*SubsrcribeResponse_EventInfo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_agent_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_agent_proto_goTypes,
		DependencyIndexes: file_protos_agent_proto_depIdxs,
		EnumInfos:         file_protos_agent_proto_enumTypes,
		MessageInfos:      file_protos_agent_proto_msgTypes,
	}.Build()
	File_protos_agent_proto = out.File
	file_protos_agent_proto_rawDesc = nil
	file_protos_agent_proto_goTypes = nil
	file_protos_agent_proto_depIdxs = nil
}
