// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/agent.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SubsrcribeResponse_MessageType int32

const (
	SubsrcribeResponse_EVENT         SubsrcribeResponse_MessageType = 0
	SubsrcribeResponse_UPLOAD_STATUS SubsrcribeResponse_MessageType = 1
	SubsrcribeResponse_UPLOAD_CANCEL SubsrcribeResponse_MessageType = 2
)

var SubsrcribeResponse_MessageType_name = map[int32]string{
	0: "EVENT",
	1: "UPLOAD_STATUS",
	2: "UPLOAD_CANCEL",
}

var SubsrcribeResponse_MessageType_value = map[string]int32{
	"EVENT":         0,
	"UPLOAD_STATUS": 1,
	"UPLOAD_CANCEL": 2,
}

func (x SubsrcribeResponse_MessageType) String() string {
	return proto.EnumName(SubsrcribeResponse_MessageType_name, int32(x))
}

func (SubsrcribeResponse_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_be14160ed34e84b5, []int{1, 0}
}

type ListManifestFilesResponse_StatusType int32

const (
	ListManifestFilesResponse_INDEXED   ListManifestFilesResponse_StatusType = 0
	ListManifestFilesResponse_SYNCED    ListManifestFilesResponse_StatusType = 1
	ListManifestFilesResponse_UPLOADING ListManifestFilesResponse_StatusType = 3
	ListManifestFilesResponse_COMPLETED ListManifestFilesResponse_StatusType = 4
	ListManifestFilesResponse_CANCELED  ListManifestFilesResponse_StatusType = 5
)

var ListManifestFilesResponse_StatusType_name = map[int32]string{
	0: "INDEXED",
	1: "SYNCED",
	3: "UPLOADING",
	4: "COMPLETED",
	5: "CANCELED",
}

var ListManifestFilesResponse_StatusType_value = map[string]int32{
	"INDEXED":   0,
	"SYNCED":    1,
	"UPLOADING": 3,
	"COMPLETED": 4,
	"CANCELED":  5,
}

func (x ListManifestFilesResponse_StatusType) String() string {
	return proto.EnumName(ListManifestFilesResponse_StatusType_name, int32(x))
}

func (ListManifestFilesResponse_StatusType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_be14160ed34e84b5, []int{11, 0}
}

type SubscribeRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeRequest) Reset()         { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()    {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be14160ed34e84b5, []int{0}
}

func (m *SubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeRequest.Unmarshal(m, b)
}
func (m *SubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeRequest.Merge(m, src)
}
func (m *SubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeRequest.Size(m)
}
func (m *SubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeRequest proto.InternalMessageInfo

func (m *SubscribeRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type SubsrcribeResponse struct {
	Type SubsrcribeResponse_MessageType `protobuf:"varint,8,opt,name=type,proto3,enum=protos.SubsrcribeResponse_MessageType" json:"type,omitempty"`
	// Types that are valid to be assigned to MessageData:
	//	*SubsrcribeResponse_UploadStatus
	//	*SubsrcribeResponse_EventInfo
	MessageData          isSubsrcribeResponse_MessageData `protobuf_oneof:"message_data"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *SubsrcribeResponse) Reset()         { *m = SubsrcribeResponse{} }
func (m *SubsrcribeResponse) String() string { return proto.CompactTextString(m) }
func (*SubsrcribeResponse) ProtoMessage()    {}
func (*SubsrcribeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_be14160ed34e84b5, []int{1}
}

func (m *SubsrcribeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubsrcribeResponse.Unmarshal(m, b)
}
func (m *SubsrcribeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubsrcribeResponse.Marshal(b, m, deterministic)
}
func (m *SubsrcribeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubsrcribeResponse.Merge(m, src)
}
func (m *SubsrcribeResponse) XXX_Size() int {
	return xxx_messageInfo_SubsrcribeResponse.Size(m)
}
func (m *SubsrcribeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubsrcribeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubsrcribeResponse proto.InternalMessageInfo

func (m *SubsrcribeResponse) GetType() SubsrcribeResponse_MessageType {
	if m != nil {
		return m.Type
	}
	return SubsrcribeResponse_EVENT
}

type isSubsrcribeResponse_MessageData interface {
	isSubsrcribeResponse_MessageData()
}

type SubsrcribeResponse_UploadStatus struct {
	UploadStatus *SubsrcribeResponse_UploadResponse `protobuf:"bytes,9,opt,name=upload_status,json=uploadStatus,proto3,oneof"`
}

type SubsrcribeResponse_EventInfo struct {
	EventInfo *SubsrcribeResponse_EventResponse `protobuf:"bytes,10,opt,name=event_info,json=eventInfo,proto3,oneof"`
}

func (*SubsrcribeResponse_UploadStatus) isSubsrcribeResponse_MessageData() {}

func (*SubsrcribeResponse_EventInfo) isSubsrcribeResponse_MessageData() {}

func (m *SubsrcribeResponse) GetMessageData() isSubsrcribeResponse_MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *SubsrcribeResponse) GetUploadStatus() *SubsrcribeResponse_UploadResponse {
	if x, ok := m.GetMessageData().(*SubsrcribeResponse_UploadStatus); ok {
		return x.UploadStatus
	}
	return nil
}

func (m *SubsrcribeResponse) GetEventInfo() *SubsrcribeResponse_EventResponse {
	if x, ok := m.GetMessageData().(*SubsrcribeResponse_EventInfo); ok {
		return x.EventInfo
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SubsrcribeResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SubsrcribeResponse_UploadStatus)(nil),
		(*SubsrcribeResponse_EventInfo)(nil),
	}
}

type SubsrcribeResponse_EventResponse struct {
	Details              string   `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubsrcribeResponse_EventResponse) Reset()         { *m = SubsrcribeResponse_EventResponse{} }
func (m *SubsrcribeResponse_EventResponse) String() string { return proto.CompactTextString(m) }
func (*SubsrcribeResponse_EventResponse) ProtoMessage()    {}
func (*SubsrcribeResponse_EventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_be14160ed34e84b5, []int{1, 0}
}

func (m *SubsrcribeResponse_EventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubsrcribeResponse_EventResponse.Unmarshal(m, b)
}
func (m *SubsrcribeResponse_EventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubsrcribeResponse_EventResponse.Marshal(b, m, deterministic)
}
func (m *SubsrcribeResponse_EventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubsrcribeResponse_EventResponse.Merge(m, src)
}
func (m *SubsrcribeResponse_EventResponse) XXX_Size() int {
	return xxx_messageInfo_SubsrcribeResponse_EventResponse.Size(m)
}
func (m *SubsrcribeResponse_EventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubsrcribeResponse_EventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubsrcribeResponse_EventResponse proto.InternalMessageInfo

func (m *SubsrcribeResponse_EventResponse) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

type SubsrcribeResponse_UploadResponse struct {
	FileId               string   `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Total                int64    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Current              int64    `protobuf:"varint,3,opt,name=current,proto3" json:"current,omitempty"`
	WorkerId             int32    `protobuf:"varint,4,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubsrcribeResponse_UploadResponse) Reset()         { *m = SubsrcribeResponse_UploadResponse{} }
func (m *SubsrcribeResponse_UploadResponse) String() string { return proto.CompactTextString(m) }
func (*SubsrcribeResponse_UploadResponse) ProtoMessage()    {}
func (*SubsrcribeResponse_UploadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_be14160ed34e84b5, []int{1, 1}
}

func (m *SubsrcribeResponse_UploadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubsrcribeResponse_UploadResponse.Unmarshal(m, b)
}
func (m *SubsrcribeResponse_UploadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubsrcribeResponse_UploadResponse.Marshal(b, m, deterministic)
}
func (m *SubsrcribeResponse_UploadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubsrcribeResponse_UploadResponse.Merge(m, src)
}
func (m *SubsrcribeResponse_UploadResponse) XXX_Size() int {
	return xxx_messageInfo_SubsrcribeResponse_UploadResponse.Size(m)
}
func (m *SubsrcribeResponse_UploadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubsrcribeResponse_UploadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubsrcribeResponse_UploadResponse proto.InternalMessageInfo

func (m *SubsrcribeResponse_UploadResponse) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

func (m *SubsrcribeResponse_UploadResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *SubsrcribeResponse_UploadResponse) GetCurrent() int64 {
	if m != nil {
		return m.Current
	}
	return 0
}

func (m *SubsrcribeResponse_UploadResponse) GetWorkerId() int32 {
	if m != nil {
		return m.WorkerId
	}
	return 0
}

type SimpleStatusResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleStatusResponse) Reset()         { *m = SimpleStatusResponse{} }
func (m *SimpleStatusResponse) String() string { return proto.CompactTextString(m) }
func (*SimpleStatusResponse) ProtoMessage()    {}
func (*SimpleStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_be14160ed34e84b5, []int{2}
}

func (m *SimpleStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleStatusResponse.Unmarshal(m, b)
}
func (m *SimpleStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleStatusResponse.Marshal(b, m, deterministic)
}
func (m *SimpleStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleStatusResponse.Merge(m, src)
}
func (m *SimpleStatusResponse) XXX_Size() int {
	return xxx_messageInfo_SimpleStatusResponse.Size(m)
}
func (m *SimpleStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleStatusResponse proto.InternalMessageInfo

func (m *SimpleStatusResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type CancelUploadRequest struct {
	ManifestId           string   `protobuf:"bytes,1,opt,name=manifest_id,json=manifestId,proto3" json:"manifest_id,omitempty"`
	CancelAll            bool     `protobuf:"varint,2,opt,name=cancel_all,json=cancelAll,proto3" json:"cancel_all,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelUploadRequest) Reset()         { *m = CancelUploadRequest{} }
func (m *CancelUploadRequest) String() string { return proto.CompactTextString(m) }
func (*CancelUploadRequest) ProtoMessage()    {}
func (*CancelUploadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be14160ed34e84b5, []int{3}
}

func (m *CancelUploadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelUploadRequest.Unmarshal(m, b)
}
func (m *CancelUploadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelUploadRequest.Marshal(b, m, deterministic)
}
func (m *CancelUploadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelUploadRequest.Merge(m, src)
}
func (m *CancelUploadRequest) XXX_Size() int {
	return xxx_messageInfo_CancelUploadRequest.Size(m)
}
func (m *CancelUploadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelUploadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelUploadRequest proto.InternalMessageInfo

func (m *CancelUploadRequest) GetManifestId() string {
	if m != nil {
		return m.ManifestId
	}
	return ""
}

func (m *CancelUploadRequest) GetCancelAll() bool {
	if m != nil {
		return m.CancelAll
	}
	return false
}

type CreateManifestRequest struct {
	BasePath             string   `protobuf:"bytes,1,opt,name=base_path,json=basePath,proto3" json:"base_path,omitempty"`
	TargetBasePath       string   `protobuf:"bytes,2,opt,name=target_base_path,json=targetBasePath,proto3" json:"target_base_path,omitempty"`
	Recursive            bool     `protobuf:"varint,3,opt,name=recursive,proto3" json:"recursive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateManifestRequest) Reset()         { *m = CreateManifestRequest{} }
func (m *CreateManifestRequest) String() string { return proto.CompactTextString(m) }
func (*CreateManifestRequest) ProtoMessage()    {}
func (*CreateManifestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be14160ed34e84b5, []int{4}
}

func (m *CreateManifestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateManifestRequest.Unmarshal(m, b)
}
func (m *CreateManifestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateManifestRequest.Marshal(b, m, deterministic)
}
func (m *CreateManifestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateManifestRequest.Merge(m, src)
}
func (m *CreateManifestRequest) XXX_Size() int {
	return xxx_messageInfo_CreateManifestRequest.Size(m)
}
func (m *CreateManifestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateManifestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateManifestRequest proto.InternalMessageInfo

func (m *CreateManifestRequest) GetBasePath() string {
	if m != nil {
		return m.BasePath
	}
	return ""
}

func (m *CreateManifestRequest) GetTargetBasePath() string {
	if m != nil {
		return m.TargetBasePath
	}
	return ""
}

func (m *CreateManifestRequest) GetRecursive() bool {
	if m != nil {
		return m.Recursive
	}
	return false
}

type AddToManifestRequest struct {
	ManifestId           string   `protobuf:"bytes,1,opt,name=manifest_id,json=manifestId,proto3" json:"manifest_id,omitempty"`
	BasePath             string   `protobuf:"bytes,2,opt,name=base_path,json=basePath,proto3" json:"base_path,omitempty"`
	TargetBasePath       string   `protobuf:"bytes,3,opt,name=target_base_path,json=targetBasePath,proto3" json:"target_base_path,omitempty"`
	Recursive            bool     `protobuf:"varint,4,opt,name=recursive,proto3" json:"recursive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddToManifestRequest) Reset()         { *m = AddToManifestRequest{} }
func (m *AddToManifestRequest) String() string { return proto.CompactTextString(m) }
func (*AddToManifestRequest) ProtoMessage()    {}
func (*AddToManifestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be14160ed34e84b5, []int{5}
}

func (m *AddToManifestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddToManifestRequest.Unmarshal(m, b)
}
func (m *AddToManifestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddToManifestRequest.Marshal(b, m, deterministic)
}
func (m *AddToManifestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddToManifestRequest.Merge(m, src)
}
func (m *AddToManifestRequest) XXX_Size() int {
	return xxx_messageInfo_AddToManifestRequest.Size(m)
}
func (m *AddToManifestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddToManifestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddToManifestRequest proto.InternalMessageInfo

func (m *AddToManifestRequest) GetManifestId() string {
	if m != nil {
		return m.ManifestId
	}
	return ""
}

func (m *AddToManifestRequest) GetBasePath() string {
	if m != nil {
		return m.BasePath
	}
	return ""
}

func (m *AddToManifestRequest) GetTargetBasePath() string {
	if m != nil {
		return m.TargetBasePath
	}
	return ""
}

func (m *AddToManifestRequest) GetRecursive() bool {
	if m != nil {
		return m.Recursive
	}
	return false
}

type RemoveFromManifestRequest struct {
	ManifestId           string   `protobuf:"bytes,1,opt,name=manifest_id,json=manifestId,proto3" json:"manifest_id,omitempty"`
	FileId               []int32  `protobuf:"varint,2,rep,packed,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFromManifestRequest) Reset()         { *m = RemoveFromManifestRequest{} }
func (m *RemoveFromManifestRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveFromManifestRequest) ProtoMessage()    {}
func (*RemoveFromManifestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be14160ed34e84b5, []int{6}
}

func (m *RemoveFromManifestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFromManifestRequest.Unmarshal(m, b)
}
func (m *RemoveFromManifestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFromManifestRequest.Marshal(b, m, deterministic)
}
func (m *RemoveFromManifestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFromManifestRequest.Merge(m, src)
}
func (m *RemoveFromManifestRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveFromManifestRequest.Size(m)
}
func (m *RemoveFromManifestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFromManifestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFromManifestRequest proto.InternalMessageInfo

func (m *RemoveFromManifestRequest) GetManifestId() string {
	if m != nil {
		return m.ManifestId
	}
	return ""
}

func (m *RemoveFromManifestRequest) GetFileId() []int32 {
	if m != nil {
		return m.FileId
	}
	return nil
}

type ListManifestsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListManifestsRequest) Reset()         { *m = ListManifestsRequest{} }
func (m *ListManifestsRequest) String() string { return proto.CompactTextString(m) }
func (*ListManifestsRequest) ProtoMessage()    {}
func (*ListManifestsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be14160ed34e84b5, []int{7}
}

func (m *ListManifestsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListManifestsRequest.Unmarshal(m, b)
}
func (m *ListManifestsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListManifestsRequest.Marshal(b, m, deterministic)
}
func (m *ListManifestsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListManifestsRequest.Merge(m, src)
}
func (m *ListManifestsRequest) XXX_Size() int {
	return xxx_messageInfo_ListManifestsRequest.Size(m)
}
func (m *ListManifestsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListManifestsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListManifestsRequest proto.InternalMessageInfo

type ListManifestsResponse struct {
	Manifests            []*ListManifestsResponse_Manifest `protobuf:"bytes,1,rep,name=manifests,proto3" json:"manifests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *ListManifestsResponse) Reset()         { *m = ListManifestsResponse{} }
func (m *ListManifestsResponse) String() string { return proto.CompactTextString(m) }
func (*ListManifestsResponse) ProtoMessage()    {}
func (*ListManifestsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_be14160ed34e84b5, []int{8}
}

func (m *ListManifestsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListManifestsResponse.Unmarshal(m, b)
}
func (m *ListManifestsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListManifestsResponse.Marshal(b, m, deterministic)
}
func (m *ListManifestsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListManifestsResponse.Merge(m, src)
}
func (m *ListManifestsResponse) XXX_Size() int {
	return xxx_messageInfo_ListManifestsResponse.Size(m)
}
func (m *ListManifestsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListManifestsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListManifestsResponse proto.InternalMessageInfo

func (m *ListManifestsResponse) GetManifests() []*ListManifestsResponse_Manifest {
	if m != nil {
		return m.Manifests
	}
	return nil
}

type ListManifestsResponse_Manifest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrganizationName     string   `protobuf:"bytes,4,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	OrganizationId       string   `protobuf:"bytes,5,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	DatasetName          string   `protobuf:"bytes,6,opt,name=dataset_name,json=datasetName,proto3" json:"dataset_name,omitempty"`
	DatasetId            string   `protobuf:"bytes,7,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	Status               string   `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListManifestsResponse_Manifest) Reset()         { *m = ListManifestsResponse_Manifest{} }
func (m *ListManifestsResponse_Manifest) String() string { return proto.CompactTextString(m) }
func (*ListManifestsResponse_Manifest) ProtoMessage()    {}
func (*ListManifestsResponse_Manifest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be14160ed34e84b5, []int{8, 0}
}

func (m *ListManifestsResponse_Manifest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListManifestsResponse_Manifest.Unmarshal(m, b)
}
func (m *ListManifestsResponse_Manifest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListManifestsResponse_Manifest.Marshal(b, m, deterministic)
}
func (m *ListManifestsResponse_Manifest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListManifestsResponse_Manifest.Merge(m, src)
}
func (m *ListManifestsResponse_Manifest) XXX_Size() int {
	return xxx_messageInfo_ListManifestsResponse_Manifest.Size(m)
}
func (m *ListManifestsResponse_Manifest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListManifestsResponse_Manifest.DiscardUnknown(m)
}

var xxx_messageInfo_ListManifestsResponse_Manifest proto.InternalMessageInfo

func (m *ListManifestsResponse_Manifest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ListManifestsResponse_Manifest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *ListManifestsResponse_Manifest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ListManifestsResponse_Manifest) GetOrganizationName() string {
	if m != nil {
		return m.OrganizationName
	}
	return ""
}

func (m *ListManifestsResponse_Manifest) GetOrganizationId() string {
	if m != nil {
		return m.OrganizationId
	}
	return ""
}

func (m *ListManifestsResponse_Manifest) GetDatasetName() string {
	if m != nil {
		return m.DatasetName
	}
	return ""
}

func (m *ListManifestsResponse_Manifest) GetDatasetId() string {
	if m != nil {
		return m.DatasetId
	}
	return ""
}

func (m *ListManifestsResponse_Manifest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type DeleteManifestRequest struct {
	ManifestId           string   `protobuf:"bytes,1,opt,name=manifest_id,json=manifestId,proto3" json:"manifest_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteManifestRequest) Reset()         { *m = DeleteManifestRequest{} }
func (m *DeleteManifestRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteManifestRequest) ProtoMessage()    {}
func (*DeleteManifestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be14160ed34e84b5, []int{9}
}

func (m *DeleteManifestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteManifestRequest.Unmarshal(m, b)
}
func (m *DeleteManifestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteManifestRequest.Marshal(b, m, deterministic)
}
func (m *DeleteManifestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteManifestRequest.Merge(m, src)
}
func (m *DeleteManifestRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteManifestRequest.Size(m)
}
func (m *DeleteManifestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteManifestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteManifestRequest proto.InternalMessageInfo

func (m *DeleteManifestRequest) GetManifestId() string {
	if m != nil {
		return m.ManifestId
	}
	return ""
}

type ListManifestFilesRequest struct {
	ManifestId           string   `protobuf:"bytes,1,opt,name=manifest_id,json=manifestId,proto3" json:"manifest_id,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListManifestFilesRequest) Reset()         { *m = ListManifestFilesRequest{} }
func (m *ListManifestFilesRequest) String() string { return proto.CompactTextString(m) }
func (*ListManifestFilesRequest) ProtoMessage()    {}
func (*ListManifestFilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be14160ed34e84b5, []int{10}
}

func (m *ListManifestFilesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListManifestFilesRequest.Unmarshal(m, b)
}
func (m *ListManifestFilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListManifestFilesRequest.Marshal(b, m, deterministic)
}
func (m *ListManifestFilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListManifestFilesRequest.Merge(m, src)
}
func (m *ListManifestFilesRequest) XXX_Size() int {
	return xxx_messageInfo_ListManifestFilesRequest.Size(m)
}
func (m *ListManifestFilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListManifestFilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListManifestFilesRequest proto.InternalMessageInfo

func (m *ListManifestFilesRequest) GetManifestId() string {
	if m != nil {
		return m.ManifestId
	}
	return ""
}

func (m *ListManifestFilesRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListManifestFilesRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type ListManifestFilesResponse struct {
	File                 []*ListManifestFilesResponse_FileUpload `protobuf:"bytes,1,rep,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *ListManifestFilesResponse) Reset()         { *m = ListManifestFilesResponse{} }
func (m *ListManifestFilesResponse) String() string { return proto.CompactTextString(m) }
func (*ListManifestFilesResponse) ProtoMessage()    {}
func (*ListManifestFilesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_be14160ed34e84b5, []int{11}
}

func (m *ListManifestFilesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListManifestFilesResponse.Unmarshal(m, b)
}
func (m *ListManifestFilesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListManifestFilesResponse.Marshal(b, m, deterministic)
}
func (m *ListManifestFilesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListManifestFilesResponse.Merge(m, src)
}
func (m *ListManifestFilesResponse) XXX_Size() int {
	return xxx_messageInfo_ListManifestFilesResponse.Size(m)
}
func (m *ListManifestFilesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListManifestFilesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListManifestFilesResponse proto.InternalMessageInfo

func (m *ListManifestFilesResponse) GetFile() []*ListManifestFilesResponse_FileUpload {
	if m != nil {
		return m.File
	}
	return nil
}

type ListManifestFilesResponse_FileUpload struct {
	Id                   int32                                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId            string                               `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SourcePath           string                               `protobuf:"bytes,3,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	TargetPath           string                               `protobuf:"bytes,4,opt,name=target_path,json=targetPath,proto3" json:"target_path,omitempty"`
	S3Key                string                               `protobuf:"bytes,5,opt,name=s3_key,json=s3Key,proto3" json:"s3_key,omitempty"`
	Status               ListManifestFilesResponse_StatusType `protobuf:"varint,6,opt,name=status,proto3,enum=protos.ListManifestFilesResponse_StatusType" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *ListManifestFilesResponse_FileUpload) Reset()         { *m = ListManifestFilesResponse_FileUpload{} }
func (m *ListManifestFilesResponse_FileUpload) String() string { return proto.CompactTextString(m) }
func (*ListManifestFilesResponse_FileUpload) ProtoMessage()    {}
func (*ListManifestFilesResponse_FileUpload) Descriptor() ([]byte, []int) {
	return fileDescriptor_be14160ed34e84b5, []int{11, 0}
}

func (m *ListManifestFilesResponse_FileUpload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListManifestFilesResponse_FileUpload.Unmarshal(m, b)
}
func (m *ListManifestFilesResponse_FileUpload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListManifestFilesResponse_FileUpload.Marshal(b, m, deterministic)
}
func (m *ListManifestFilesResponse_FileUpload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListManifestFilesResponse_FileUpload.Merge(m, src)
}
func (m *ListManifestFilesResponse_FileUpload) XXX_Size() int {
	return xxx_messageInfo_ListManifestFilesResponse_FileUpload.Size(m)
}
func (m *ListManifestFilesResponse_FileUpload) XXX_DiscardUnknown() {
	xxx_messageInfo_ListManifestFilesResponse_FileUpload.DiscardUnknown(m)
}

var xxx_messageInfo_ListManifestFilesResponse_FileUpload proto.InternalMessageInfo

func (m *ListManifestFilesResponse_FileUpload) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ListManifestFilesResponse_FileUpload) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *ListManifestFilesResponse_FileUpload) GetSourcePath() string {
	if m != nil {
		return m.SourcePath
	}
	return ""
}

func (m *ListManifestFilesResponse_FileUpload) GetTargetPath() string {
	if m != nil {
		return m.TargetPath
	}
	return ""
}

func (m *ListManifestFilesResponse_FileUpload) GetS3Key() string {
	if m != nil {
		return m.S3Key
	}
	return ""
}

func (m *ListManifestFilesResponse_FileUpload) GetStatus() ListManifestFilesResponse_StatusType {
	if m != nil {
		return m.Status
	}
	return ListManifestFilesResponse_INDEXED
}

type UploadManifestRequest struct {
	ManifestId           string   `protobuf:"bytes,1,opt,name=manifest_id,json=manifestId,proto3" json:"manifest_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadManifestRequest) Reset()         { *m = UploadManifestRequest{} }
func (m *UploadManifestRequest) String() string { return proto.CompactTextString(m) }
func (*UploadManifestRequest) ProtoMessage()    {}
func (*UploadManifestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be14160ed34e84b5, []int{12}
}

func (m *UploadManifestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadManifestRequest.Unmarshal(m, b)
}
func (m *UploadManifestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadManifestRequest.Marshal(b, m, deterministic)
}
func (m *UploadManifestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadManifestRequest.Merge(m, src)
}
func (m *UploadManifestRequest) XXX_Size() int {
	return xxx_messageInfo_UploadManifestRequest.Size(m)
}
func (m *UploadManifestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadManifestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadManifestRequest proto.InternalMessageInfo

func (m *UploadManifestRequest) GetManifestId() string {
	if m != nil {
		return m.ManifestId
	}
	return ""
}

type GetUserRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be14160ed34e84b5, []int{13}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

type UserResponse struct {
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	SessionToken         string   `protobuf:"bytes,4,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	TokenExpire          int64    `protobuf:"varint,5,opt,name=token_expire,json=tokenExpire,proto3" json:"token_expire,omitempty"`
	Profile              string   `protobuf:"bytes,8,opt,name=profile,proto3" json:"profile,omitempty"`
	Environment          string   `protobuf:"bytes,9,opt,name=environment,proto3" json:"environment,omitempty"`
	OrganizationId       string   `protobuf:"bytes,10,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	OrganizationName     string   `protobuf:"bytes,11,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_be14160ed34e84b5, []int{14}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserResponse) GetSessionToken() string {
	if m != nil {
		return m.SessionToken
	}
	return ""
}

func (m *UserResponse) GetTokenExpire() int64 {
	if m != nil {
		return m.TokenExpire
	}
	return 0
}

func (m *UserResponse) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

func (m *UserResponse) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

func (m *UserResponse) GetOrganizationId() string {
	if m != nil {
		return m.OrganizationId
	}
	return ""
}

func (m *UserResponse) GetOrganizationName() string {
	if m != nil {
		return m.OrganizationName
	}
	return ""
}

//
type SwitchProfileRequest struct {
	Profile              string   `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SwitchProfileRequest) Reset()         { *m = SwitchProfileRequest{} }
func (m *SwitchProfileRequest) String() string { return proto.CompactTextString(m) }
func (*SwitchProfileRequest) ProtoMessage()    {}
func (*SwitchProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be14160ed34e84b5, []int{15}
}

func (m *SwitchProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchProfileRequest.Unmarshal(m, b)
}
func (m *SwitchProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchProfileRequest.Marshal(b, m, deterministic)
}
func (m *SwitchProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchProfileRequest.Merge(m, src)
}
func (m *SwitchProfileRequest) XXX_Size() int {
	return xxx_messageInfo_SwitchProfileRequest.Size(m)
}
func (m *SwitchProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchProfileRequest proto.InternalMessageInfo

func (m *SwitchProfileRequest) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

type ReAuthenticateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReAuthenticateRequest) Reset()         { *m = ReAuthenticateRequest{} }
func (m *ReAuthenticateRequest) String() string { return proto.CompactTextString(m) }
func (*ReAuthenticateRequest) ProtoMessage()    {}
func (*ReAuthenticateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be14160ed34e84b5, []int{16}
}

func (m *ReAuthenticateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReAuthenticateRequest.Unmarshal(m, b)
}
func (m *ReAuthenticateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReAuthenticateRequest.Marshal(b, m, deterministic)
}
func (m *ReAuthenticateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReAuthenticateRequest.Merge(m, src)
}
func (m *ReAuthenticateRequest) XXX_Size() int {
	return xxx_messageInfo_ReAuthenticateRequest.Size(m)
}
func (m *ReAuthenticateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReAuthenticateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReAuthenticateRequest proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("protos.SubsrcribeResponse_MessageType", SubsrcribeResponse_MessageType_name, SubsrcribeResponse_MessageType_value)
	proto.RegisterEnum("protos.ListManifestFilesResponse_StatusType", ListManifestFilesResponse_StatusType_name, ListManifestFilesResponse_StatusType_value)
	proto.RegisterType((*SubscribeRequest)(nil), "protos.SubscribeRequest")
	proto.RegisterType((*SubsrcribeResponse)(nil), "protos.SubsrcribeResponse")
	proto.RegisterType((*SubsrcribeResponse_EventResponse)(nil), "protos.SubsrcribeResponse.EventResponse")
	proto.RegisterType((*SubsrcribeResponse_UploadResponse)(nil), "protos.SubsrcribeResponse.UploadResponse")
	proto.RegisterType((*SimpleStatusResponse)(nil), "protos.SimpleStatusResponse")
	proto.RegisterType((*CancelUploadRequest)(nil), "protos.CancelUploadRequest")
	proto.RegisterType((*CreateManifestRequest)(nil), "protos.CreateManifestRequest")
	proto.RegisterType((*AddToManifestRequest)(nil), "protos.AddToManifestRequest")
	proto.RegisterType((*RemoveFromManifestRequest)(nil), "protos.RemoveFromManifestRequest")
	proto.RegisterType((*ListManifestsRequest)(nil), "protos.ListManifestsRequest")
	proto.RegisterType((*ListManifestsResponse)(nil), "protos.ListManifestsResponse")
	proto.RegisterType((*ListManifestsResponse_Manifest)(nil), "protos.ListManifestsResponse.Manifest")
	proto.RegisterType((*DeleteManifestRequest)(nil), "protos.DeleteManifestRequest")
	proto.RegisterType((*ListManifestFilesRequest)(nil), "protos.ListManifestFilesRequest")
	proto.RegisterType((*ListManifestFilesResponse)(nil), "protos.ListManifestFilesResponse")
	proto.RegisterType((*ListManifestFilesResponse_FileUpload)(nil), "protos.ListManifestFilesResponse.FileUpload")
	proto.RegisterType((*UploadManifestRequest)(nil), "protos.UploadManifestRequest")
	proto.RegisterType((*GetUserRequest)(nil), "protos.GetUserRequest")
	proto.RegisterType((*UserResponse)(nil), "protos.UserResponse")
	proto.RegisterType((*SwitchProfileRequest)(nil), "protos.SwitchProfileRequest")
	proto.RegisterType((*ReAuthenticateRequest)(nil), "protos.ReAuthenticateRequest")
}

func init() { proto.RegisterFile("protos/agent.proto", fileDescriptor_be14160ed34e84b5) }

var fileDescriptor_be14160ed34e84b5 = []byte{
	// 1265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0xdb, 0x6e, 0xdb, 0x46,
	0x13, 0xd6, 0x59, 0xe2, 0xe8, 0xf0, 0x33, 0xfb, 0xcb, 0x8e, 0xa2, 0xc4, 0x88, 0xc2, 0x02, 0xad,
	0x82, 0x34, 0x4a, 0x90, 0xdc, 0xb4, 0xbd, 0x28, 0x2a, 0x4b, 0x8c, 0x2b, 0xc4, 0x96, 0x5d, 0x4a,
	0xea, 0x21, 0x37, 0x02, 0x2d, 0xae, 0xec, 0x85, 0x29, 0x52, 0xe5, 0xae, 0x94, 0xba, 0xe8, 0x45,
	0x1f, 0xa0, 0x7d, 0x83, 0x3e, 0x59, 0xaf, 0xf2, 0x10, 0x7d, 0x80, 0x62, 0x77, 0x49, 0x91, 0xb4,
	0x69, 0xcb, 0x41, 0xef, 0x3c, 0x1f, 0x67, 0x3e, 0xef, 0xcc, 0xce, 0x37, 0xb3, 0x02, 0xb4, 0xf4,
	0x5c, 0xe6, 0xd2, 0x17, 0xe6, 0x19, 0x76, 0x58, 0x47, 0x18, 0xa8, 0x20, 0x31, 0x4d, 0x03, 0x75,
	0xb4, 0x3a, 0xa5, 0x33, 0x8f, 0x9c, 0x62, 0x03, 0xff, 0xbc, 0xc2, 0x94, 0xa1, 0x1a, 0x64, 0x88,
	0xd5, 0x48, 0xb7, 0xd2, 0xed, 0xbc, 0x91, 0x21, 0x96, 0xf6, 0x21, 0x0b, 0x88, 0x3b, 0x79, 0xbe,
	0x17, 0x5d, 0xba, 0x0e, 0xc5, 0xe8, 0x2b, 0xc8, 0xb1, 0xcb, 0x25, 0x6e, 0x94, 0x5a, 0xe9, 0x76,
	0xed, 0xd5, 0xa7, 0x92, 0x98, 0x76, 0xae, 0x7b, 0x76, 0x8e, 0x30, 0xa5, 0xe6, 0x19, 0x1e, 0x5f,
	0x2e, 0xb1, 0x21, 0x62, 0xd0, 0x09, 0x54, 0x57, 0x4b, 0xdb, 0x35, 0xad, 0x29, 0x65, 0x26, 0x5b,
	0xd1, 0x86, 0xd2, 0x4a, 0xb7, 0xcb, 0xaf, 0x9e, 0xde, 0x42, 0x32, 0x11, 0xfe, 0x81, 0xf9, 0x6d,
	0xca, 0xa8, 0x48, 0x86, 0x91, 0x20, 0x40, 0x03, 0x00, 0xbc, 0xc6, 0x0e, 0x9b, 0x12, 0x67, 0xee,
	0x36, 0x40, 0xd0, 0xb5, 0x6f, 0xa1, 0xd3, 0xb9, 0x73, 0x84, 0x4d, 0x11, 0xd1, 0x03, 0x67, 0xee,
	0x36, 0x9f, 0x42, 0x35, 0xf6, 0x15, 0x35, 0xa0, 0x68, 0x61, 0x66, 0x12, 0x9b, 0x8a, 0xaa, 0x28,
	0x46, 0x60, 0x36, 0xd7, 0x50, 0x8b, 0x9f, 0x0b, 0xdd, 0x87, 0xe2, 0x9c, 0xd8, 0x78, 0xea, 0x57,
	0x50, 0x31, 0x0a, 0xdc, 0x1c, 0x58, 0xa8, 0x0e, 0x79, 0xe6, 0x32, 0xd3, 0x6e, 0x64, 0x5a, 0xe9,
	0x76, 0xd6, 0x90, 0x06, 0xa7, 0x9e, 0xad, 0x3c, 0x0f, 0x3b, 0xac, 0x91, 0x15, 0x78, 0x60, 0xa2,
	0x87, 0xa0, 0xbc, 0x77, 0xbd, 0x0b, 0xec, 0x71, 0xaa, 0x9c, 0xb8, 0x8c, 0x92, 0x04, 0x06, 0x96,
	0xf6, 0x35, 0x94, 0x23, 0x45, 0x45, 0x0a, 0xe4, 0xf5, 0xef, 0xf5, 0xe1, 0x58, 0x4d, 0xa1, 0x7b,
	0x50, 0x9d, 0x9c, 0x1c, 0x1e, 0x77, 0xfb, 0xd3, 0xd1, 0xb8, 0x3b, 0x9e, 0x8c, 0xd4, 0x74, 0x04,
	0xea, 0x75, 0x87, 0x3d, 0xfd, 0x50, 0xcd, 0xec, 0xd7, 0xa0, 0xb2, 0x90, 0xf1, 0x53, 0xcb, 0x64,
	0xa6, 0xd6, 0x81, 0xfa, 0x88, 0x2c, 0x96, 0x36, 0x96, 0xd5, 0xdc, 0x64, 0xb3, 0x0b, 0x05, 0xff,
	0x82, 0xfc, 0x64, 0xa4, 0xa5, 0x4d, 0xe0, 0xff, 0x3d, 0xd3, 0x99, 0x61, 0x3b, 0xc8, 0x5e, 0x76,
	0xce, 0x63, 0x28, 0x2f, 0x4c, 0x87, 0xcc, 0x31, 0x65, 0x61, 0x01, 0x20, 0x80, 0x06, 0x16, 0xda,
	0x03, 0x98, 0x89, 0xb8, 0xa9, 0x69, 0xcb, 0x4a, 0x94, 0x0c, 0x45, 0x22, 0x5d, 0xdb, 0xd6, 0x7e,
	0x83, 0x9d, 0x9e, 0x87, 0x4d, 0x86, 0x8f, 0xfc, 0x90, 0x80, 0xf8, 0x21, 0x28, 0xa7, 0x26, 0xc5,
	0xd3, 0xa5, 0xc9, 0xce, 0x7d, 0xda, 0x12, 0x07, 0x4e, 0x4c, 0x76, 0x8e, 0xda, 0xa0, 0x32, 0xd3,
	0x3b, 0xc3, 0x6c, 0x1a, 0xfa, 0x64, 0x84, 0x4f, 0x4d, 0xe2, 0xfb, 0x81, 0xe7, 0x23, 0x50, 0x3c,
	0x3c, 0x5b, 0x79, 0x94, 0xac, 0xb1, 0xa8, 0x77, 0xc9, 0x08, 0x01, 0xed, 0xaf, 0x34, 0xd4, 0xbb,
	0x96, 0x35, 0x76, 0xaf, 0xfe, 0xf7, 0xad, 0x69, 0xc5, 0x8e, 0x97, 0xb9, 0xc3, 0xf1, 0xb2, 0xdb,
	0x8f, 0x97, 0xbb, 0x7a, 0xbc, 0x09, 0x3c, 0x30, 0xf0, 0xc2, 0x5d, 0xe3, 0x37, 0x9e, 0xbb, 0xf8,
	0xe8, 0x23, 0x46, 0xfa, 0x32, 0xd3, 0xca, 0xb6, 0xf3, 0x41, 0x5f, 0x6a, 0xbb, 0x50, 0x3f, 0x24,
	0x94, 0x05, 0x84, 0xd4, 0x67, 0xd4, 0x3e, 0x64, 0x60, 0xe7, 0xca, 0x07, 0xbf, 0x29, 0xfa, 0xa0,
	0x04, 0xc4, 0xbc, 0x2f, 0xb2, 0xed, 0x72, 0xa8, 0xfe, 0xc4, 0x88, 0xce, 0xe6, 0xb4, 0x61, 0x60,
	0xf3, 0xf7, 0x0c, 0x94, 0x02, 0x3c, 0x32, 0x72, 0x14, 0x3e, 0x72, 0x78, 0x41, 0x57, 0x14, 0x7b,
	0x53, 0xc7, 0x5c, 0xe0, 0xa0, 0xa0, 0x1c, 0x18, 0x9a, 0x0b, 0x21, 0x31, 0xf1, 0x91, 0x58, 0x7e,
	0x1d, 0x0b, 0xdc, 0x1c, 0x58, 0xe8, 0x19, 0xdc, 0x73, 0xbd, 0x33, 0xd3, 0x21, 0xbf, 0x9a, 0x8c,
	0xb8, 0x8e, 0x8c, 0xce, 0x09, 0x17, 0x35, 0xfa, 0x41, 0xb0, 0x7c, 0x06, 0xff, 0x8b, 0x39, 0x13,
	0xab, 0x91, 0x97, 0xb7, 0x12, 0x85, 0x07, 0x16, 0x7a, 0x02, 0x15, 0xae, 0x11, 0x8a, 0x99, 0x24,
	0x2c, 0x08, 0xaf, 0xb2, 0x8f, 0x09, 0xae, 0x3d, 0x80, 0xc0, 0x85, 0x58, 0x8d, 0xa2, 0x70, 0x50,
	0x7c, 0x64, 0x60, 0x45, 0x54, 0x54, 0x8a, 0xa9, 0xe8, 0x0b, 0xd8, 0xe9, 0x63, 0x1b, 0x5f, 0x6f,
	0xf7, 0x6d, 0xb7, 0xa9, 0x11, 0x68, 0x44, 0x2b, 0xfd, 0x86, 0xd8, 0x98, 0xde, 0xb9, 0x15, 0x76,
	0xa1, 0xe0, 0xce, 0xe7, 0x14, 0x33, 0x51, 0xd9, 0xbc, 0xe1, 0x5b, 0x7c, 0x42, 0xd9, 0x64, 0x41,
	0xe4, 0x24, 0xca, 0x1b, 0xd2, 0xd0, 0xfe, 0xcc, 0xc2, 0x83, 0x84, 0xff, 0xe5, 0xf7, 0xc2, 0x37,
	0x90, 0xe3, 0x7d, 0xe4, 0xb7, 0xc1, 0xe7, 0x49, 0x6d, 0x10, 0x0b, 0xe8, 0x70, 0xcb, 0x1f, 0x1a,
	0x22, 0xb2, 0xf9, 0x77, 0x1a, 0x20, 0x04, 0xaf, 0x2e, 0x1f, 0x5e, 0x5a, 0x8a, 0x29, 0xf5, 0x6f,
	0x48, 0xb6, 0x82, 0xe2, 0x23, 0x03, 0x8b, 0x27, 0x4b, 0xdd, 0x95, 0x37, 0x8b, 0xe9, 0x0a, 0x24,
	0x24, 0x34, 0xf5, 0x18, 0xca, 0xbe, 0xfa, 0x84, 0x83, 0xec, 0x06, 0x90, 0x90, 0x70, 0xd8, 0x81,
	0x02, 0x7d, 0x3d, 0xbd, 0xc0, 0x97, 0xfe, 0xf5, 0xe7, 0xe9, 0xeb, 0xb7, 0xf8, 0x12, 0xf5, 0x37,
	0x77, 0x56, 0x10, 0xfb, 0xed, 0x0e, 0xa9, 0xc9, 0xd9, 0x29, 0xb6, 0x5c, 0x70, 0xc3, 0xdf, 0x01,
	0x84, 0x28, 0x2a, 0x43, 0x71, 0x30, 0xec, 0xeb, 0x3f, 0xea, 0x7d, 0x35, 0x85, 0x00, 0x0a, 0xa3,
	0x9f, 0x86, 0x3d, 0xbd, 0xaf, 0xa6, 0x51, 0x15, 0x14, 0x39, 0xa1, 0x07, 0xc3, 0x03, 0x35, 0xcb,
	0xcd, 0xde, 0xf1, 0xd1, 0xc9, 0xa1, 0x3e, 0xd6, 0xfb, 0x6a, 0x0e, 0x55, 0xa0, 0x24, 0x07, 0xb7,
	0xde, 0x57, 0xf3, 0xbc, 0x69, 0x64, 0xa9, 0x3e, 0xba, 0x69, 0x54, 0xa8, 0x1d, 0x60, 0x36, 0xa1,
	0xd8, 0x0b, 0x34, 0xfe, 0x47, 0x06, 0x2a, 0xd2, 0xf6, 0xaf, 0x53, 0x56, 0x3f, 0xb3, 0xd1, 0x21,
	0x82, 0x9c, 0xe8, 0x79, 0x59, 0x57, 0xf1, 0x37, 0xfa, 0x04, 0xaa, 0xc1, 0x8d, 0x30, 0xf7, 0x02,
	0x3b, 0x7e, 0x4d, 0x2b, 0x3e, 0x38, 0xe6, 0x18, 0x17, 0x8d, 0xf8, 0x38, 0xc5, 0xbf, 0x2c, 0x89,
	0x87, 0x45, 0x6d, 0xb3, 0x46, 0x59, 0x60, 0xba, 0x80, 0xf8, 0xea, 0x5b, 0x7a, 0xae, 0xe8, 0x1e,
	0x29, 0x8b, 0xc0, 0x44, 0x2d, 0x28, 0x63, 0x67, 0x4d, 0x3c, 0xd7, 0x59, 0xf0, 0xc5, 0xa8, 0x48,
	0xc1, 0x45, 0xa0, 0x24, 0xf1, 0x42, 0xa2, 0x78, 0x13, 0x47, 0x42, 0x39, 0x79, 0x24, 0x68, 0x2f,
	0xa1, 0x3e, 0x7a, 0x4f, 0xd8, 0xec, 0xfc, 0x44, 0x1e, 0x24, 0xa8, 0x6c, 0xe4, 0xa4, 0xe9, 0xd8,
	0x49, 0xb5, 0xfb, 0xb0, 0x63, 0xe0, 0xee, 0x8a, 0x9d, 0x63, 0x87, 0x91, 0x99, 0xc9, 0x82, 0x90,
	0x57, 0xff, 0x14, 0x21, 0xdf, 0xe5, 0xef, 0x2d, 0x74, 0x0c, 0xb5, 0xf8, 0x4e, 0x43, 0x7b, 0x41,
	0x2b, 0x25, 0xee, 0xba, 0xe6, 0xa3, 0xcd, 0xab, 0x25, 0x61, 0x23, 0x6b, 0x29, 0x74, 0x04, 0xd5,
	0xd8, 0x96, 0x42, 0x9b, 0x80, 0xa4, 0xe5, 0xb5, 0x95, 0xee, 0x07, 0x40, 0xd7, 0xd7, 0x0a, 0x7a,
	0x12, 0x44, 0xdd, 0xb8, 0x72, 0xb6, 0x12, 0x1f, 0x43, 0x2d, 0x3e, 0xdd, 0xc2, 0xc4, 0x13, 0xa7,
	0xde, 0x56, 0xc2, 0x21, 0x54, 0x63, 0xeb, 0x25, 0x4c, 0x3c, 0x69, 0x81, 0x35, 0xf7, 0x6e, 0xdd,
	0x49, 0x5a, 0x0a, 0xbd, 0x83, 0x7b, 0xd7, 0xc4, 0x8c, 0x5a, 0xb7, 0xe8, 0x5c, 0xf2, 0x3e, 0xd9,
	0x3a, 0x09, 0x64, 0xf2, 0x71, 0x95, 0x86, 0xc9, 0x27, 0xaa, 0x77, 0x6b, 0xf2, 0x6f, 0xa1, 0x12,
	0x7d, 0x71, 0xa1, 0x87, 0x9b, 0x26, 0xba, 0xfe, 0x0e, 0xdb, 0x4a, 0xa6, 0x83, 0xb2, 0x79, 0xf5,
	0xa3, 0x46, 0xf4, 0x95, 0x1c, 0xfd, 0x21, 0xd0, 0x6c, 0xde, 0xfc, 0x7e, 0xd6, 0x52, 0x2f, 0xd3,
	0x48, 0x87, 0xf2, 0xc4, 0xa1, 0xff, 0x95, 0x08, 0x7d, 0x09, 0x45, 0x7f, 0x2e, 0xa1, 0xdd, 0xc0,
	0x31, 0x3e, 0xa8, 0x9a, 0xf5, 0x4d, 0xf1, 0x22, 0xd3, 0x4a, 0x24, 0x52, 0x8d, 0x29, 0x36, 0x6c,
	0x89, 0x24, 0x21, 0xdf, 0x48, 0x73, 0x00, 0xb5, 0xb8, 0x8c, 0xc3, 0xdb, 0x4a, 0x94, 0xf7, 0x4d,
	0x44, 0xfb, 0xcf, 0xdf, 0x3d, 0x3b, 0x23, 0xec, 0x7c, 0x75, 0xda, 0x99, 0xb9, 0x8b, 0x17, 0x4b,
	0xec, 0x38, 0x94, 0xe0, 0x35, 0x0e, 0xff, 0x7a, 0x2e, 0x7e, 0x84, 0xbd, 0x90, 0xd1, 0xa7, 0xf2,
	0x57, 0xd8, 0xeb, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x49, 0x65, 0x17, 0xa2, 0x0d, 0x00,
	0x00,
}
