name: Docker Image CI

on:
  push:
    branches: [ "main", "athril"]
  pull_request:
    branches: [ "main", "athril"]

jobs:
  container-job:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.18"]
        python-version: ["3.10"]
        os: [ubuntu-latest] 

    container: 
      image: ${{ env.DOCKER_HUB_USERNAME }}/pennsieve-agent:latest
      
    services:
      pennsieve-agent:
        image: ${{ env..DOCKER_HUB_USERNAME }}/pennsieve-agent:latest
        ports: 
          - 9000:9000
    steps:
    - uses: actions/checkout@v3
    - name: Set up GO {{matrix.go-version}}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Pennsieve Agent
      run: |
        sudo apt-get update
        sudo apt-get install jq
        AGENT_VERSION=$(curl https://api.github.com/repos/pennsieve/pennsieve-agent/releases -s | jq -r .[].tag_name | grep '^[0-9]*\.[0-9]*\.[0-9]*$' -m1)
        wget https://github.com/Pennsieve/pennsieve-agent/releases/download/${AGENT_VERSION}/pennsieve-agent_${AGENT_VERSION}_amd64.deb
        sudo apt install ./pennsieve-agent_${AGENT_VERSION}_amd64.deb 
        pennsieve config init ~/.pennsieve/config.ini --api_token ${{ env.API_KEY }} --api_secret ${{ env.API_SECRET }} -f
        pennsieve agent 
        pennsieve version
    
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag pennsieve-agent:$(date +%s)
 
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pennsieve-agent:latest

  
