# This is a basic workflow to help you get started with Actions

name: Publish-Release

# Controls when the workflow will run
on:
  push:
    tags:
      - '*.*.*'  # Match anything resembling semver

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  xgo:
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - 1.18
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build with xgo
        uses: crazy-max/ghaction-xgo@v1
        with:
          xgo_version: latest
          go_version: ${{ matrix.go_version }}
          dest: build
          prefix: myapp
          targets: windows/386,windows/amd64,linux/386,linux/amd64,darwin/386,darwin/amd64
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default
